<template>
<div>
	<div v-if="country ==='Nigeria' "  class="col-md-12 alert toke hidden-xs">
		<p class="mt-20"><i class="entypo-bookmark" style="color: #bbb !important;"></i><b>Wallet Guide</b></p><br>
		<p class="text-semibold">
			<b>Minimum amount to recharge is ₦3000.</b> <br />
			You can use any of our autogenerated virtual account numbers to topup your wallet and any money transferred to these account numbers would be credited to your wallet automatically.
			<br>
			If you experience any issue making payment to your wallet, please reach out to <a href="mailto:sales@termii.com">sales@termii.com</a> or contact any of your account reps via our support channels.</p>
	</div>
	<div v-if="country !== 'Nigeria'"  class="col-md-12 alert toke hidden-xs" >
		<p><i class="entypo-info-circled" style="color: #bbb !important;"></i> <b>Bank Transfer Guide:</b></p><br>
		<p style="text-align:justify">
			For US or international customers, please make payment to the bank above and include the following details:
			<br>
			<br>
			<b>ABA Routing Number:</b>
			<br/>
			021000021
			<br>
			<br>
			<b>Company Address:</b>
			<br>
			601 Pennsylvania Avenue, NW South Building Suite 920, Washington D.C. 20004.
			<br>
			<br>
			Additional Wire Instructions For direct deposits and ACH transactions use routing number: 044000037
		</p>
	</div>
</div>
</template>

<script>
export default {
name: "TransactionGuide",
data(){
	return{
	country:	JSON.parse(localStorage.getItem('user_data')).country
	}
}

}
</script>

<style scoped>

</style>
